baseURL = "https://zblanks.github.io/"
languageCode = 'en-us'
title = 'Zachary Blanks'
theme = 'hugo-resume'

[params]
address = "Washington, DC"
email = "zdb6dz@virginia.edu"
firstName = "Zachary"
lastName = "Blanks"
profileImage = "img/zach-biking.jpg"
showContact = false
sections = ["publications","education"]

[[params.handles]]
link = "https://github.com/zblanks/"
name = "GitHub"
